# Be a good community member
exec	"rtstats -h rtstats.unidata.ucar.edu"
# Process locally so that we can do nagios checks
exec	"rtstats"
# The one action to save rtstats
exec	"pqact -f EXP /home/meteor_ldm/etc/pqact.conf"

#### REQUEST SECTION
request	WMO	".*"	idd.agron.iastate.edu

##### ALLOW SECTION

# Thomas Perretta
allow	IDS|DDPLUS	^18\.224\.234\.226$

# Henry Farmer
allow	IDS|DDPLUS	^34\.242\.17\.146$

# Required for life to work the way it should
ACCEPT ANY	".*"	localhost
