# Be a good community member
exec	"rtstats -h rtstats.unidata.ucar.edu"
# Process locally so that we can do nagios checks
exec	"rtstats"
# The one action to save rtstats
exec	"pqact -f EXP /home/meteor_ldm/etc/pqact.conf"

#### REQUEST SECTION
request	WMO	".*"	idd.agron.iastate.edu

##### ALLOW SECTION

# Chris Alonso
allow	IDS|DDPLUS	^54\.225\.174\.220$

# Derek Cui
allow	IDS|DDPLUS	^132\.145\.165\.216$

# John McFall
allow	IDS|DDPLUS	^5\.78\.24\.234$
allow	IDS|DDPLUS	^209\.97\.158\.37$

# Jack
allow	IDS|DDPLUS	^161\.35\.116\.244$

# Thomas Perretta
allow	IDS|DDPLUS	^18\.224\.234\.226$

# Henry Farmer
allow	IDS|DDPLUS	^52\.211\.226\.83$

# Vienna Austria
allow	IDS|DDPLUS	^91\.244\.70\.36$

# Aidan Ahram
allow	IDS|DDPLUS	^35\.209\.120\.80$

# Sergio Vargas
allow	IDS|DDPLUS	^79-117-191-20\.digimobil\.es$

# Daniel Reynolds
allow	IDS|DDPLUS	^weatherbox\.xyz$

# Required for life to work the way it should
ACCEPT ANY	".*"	localhost
