# Be a good community member
exec	"rtstats -h rtstats.unidata.ucar.edu"
# Process locally so that we can do nagios checks
exec	"rtstats"
# The one action to save rtstats
exec	"pqact -f EXP /home/meteor_ldm/etc/pqact.conf"

#### REQUEST SECTION
request	WMO	".*"	idd.agron.iastate.edu

##### ALLOW SECTION

# Sean Nourrie
allow	IDS|DDPLUS	^159\.89\.92\.132$

# Eric Weinberg
allow	IDS|DDPLUS	^68\.66\.120\.133$

# Cody Negri
allow	IDS|DDPLUS	^143\.244\.167\.71$

# Moises Aguilar
allow	IDS|DDPLUS	^107\.218\.6\.80$

# Andrey Schurko
allow	IDS|DDPLUS	^93\.85\.234\.221$

# Mithran
allow	IDS|DDPLUS	^108\.61\.128\.24$

# Ian Masterson
allow	IDS|DDPLUS	^165\.245\.149\.15$
allow	IDS|DDPLUS	^165\.245\.171\.44$

# Alex Fish
allow	IDS|DDPLUS	^3\.23\.1\.132$

# Daniel Batista
allow	IDS|DDPLUS	^34\.194\.77\.254$

# Chris Alonso
allow	IDS|DDPLUS	^54\.225\.174\.220$

# 12 w1
allow	IDS|DDPLUS	^144\.202\.127\.31$

# Derek Cui
allow	IDS|DDPLUS	^132\.145\.165\.216$

# John McFall
allow	IDS|DDPLUS	^5\.78\.24\.234$
allow	IDS|DDPLUS	^209\.97\.158\.37$

# Jack
allow	IDS|DDPLUS	^161\.35\.116\.244$

# Thomas Perretta
allow	IDS|DDPLUS	^18\.224\.234\.226$

# Henry Farmer
allow	IDS|DDPLUS	^52\.211\.226\.83$

# Vienna Austria
allow	IDS|DDPLUS	^91\.244\.70\.36$

# Aidan Ahram
allow	IDS|DDPLUS	^35\.209\.120\.80$

# Sergio Vargas
allow	IDS|DDPLUS	^79-117-191-20\.digimobil\.es$

# Daniel Reynolds
allow	IDS|DDPLUS	^weatherbox\.xyz$

# Required for life to work the way it should
ACCEPT ANY	".*"	localhost
