###
# Save text for archival to box and other places, don't trust the timestamps
# on the WMO header, but just use the system time
# Yuck, prevent SDCN01 (Canadian RADAR) from polluting this
# LDU grib data, alas
IDS|DDPLUS	^([^S]|S[^D]|SD[^C]|SDC[^N])
	FILE	-close	/mesonet/tmp/offline/text/%Y%m%d%H.txt

